name: test

on: [push]
branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Go
        uses: actions/set-go@v5
        with:
          go-version: "1.23.0"
  
