name: test

on: 
  push:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
              go-version: "1.23.0"
      
      - name: run tests
        run: make

